name: Build backend

on:
  push:
    branches:
      - main
    paths-ignore:
      - frontend/*

permissions:
  actions: read

jobs:
  build-backend:
    name: Build backend for lobby
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Build app
        run: |
          cd app
          go build main.go
